// This file is automatically generated. Do not edit it directly.
import { createClient, type Session } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const RECOVERY_EVENT_KEY = "dtr-password-recovery-event-user";
let recoveryEventMarker: string | null = null;

// Only extracts a non-secret identity for comparison; Supabase validates tokens.
function sessionMarker(session: Session | null): string | null {
  if (!session) return null;
  try {
    const payload = session.access_token.split(".")[1].replace(/-/g, "+").replace(/_/g, "/");
    const claims = JSON.parse(atob(payload));
    return typeof claims.session_id === "string" && claims.sub === session.user.id
      ? JSON.stringify([session.user.id, claims.session_id])
      : null;
  } catch {
    return null;
  }
}

export function getPasswordRecoverySession(session: Session | null): string | null {
  let marker = recoveryEventMarker;
  try {
    marker ||= typeof window !== "undefined" ? window.sessionStorage.getItem(RECOVERY_EVENT_KEY) : null;
  } catch { /* Storage may be unavailable; the in-memory marker still works. */ }
  return marker && marker === sessionMarker(session) ? marker : null;
}

export function clearPasswordRecoveryEvent(): void {
  recoveryEventMarker = null;
  try {
    if (typeof window !== "undefined") window.sessionStorage.removeItem(RECOVERY_EVENT_KEY);
  } catch { /* Storage may be unavailable. */ }
}

function createSupabaseClient(isolated = false) {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      ...(isolated ? { storageKey: `dtr-recovery-${crypto.randomUUID()}` } : {}),
      storage: !isolated && typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: !isolated,
      autoRefreshToken: !isolated,
      detectSessionInUrl: !isolated,
    }
  });

  // Capture PASSWORD_RECOVERY even when Supabase finishes URL processing
  // before the reset page's React effect subscribes.
  if (!isolated && typeof window !== "undefined") {
    client.auth.onAuthStateChange((event, session) => {
      if (event === "PASSWORD_RECOVERY") {
        clearPasswordRecoveryEvent();
        recoveryEventMarker = sessionMarker(session);
        try {
          if (recoveryEventMarker) window.sessionStorage.setItem(RECOVERY_EVENT_KEY, recoveryEventMarker);
        } catch { /* Keep the marker in memory when storage is unavailable. */ }
      } else if (event === "SIGNED_OUT" || !getPasswordRecoverySession(session)) {
        clearPasswordRecoveryEvent();
      }
    });
  }

  return client;
}

export async function updateRecoveryPassword(session: Session, password: string) {
  // Pin the write to the verified recovery session, even if another tab signs
  // into a different account while this request is pending. Never persist it.
  const client = createSupabaseClient(true);
  const { error } = await client.auth.setSession(session);
  if (error) throw error;
  return client.auth.updateUser({ password });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

